### ISSUE TITLE
Intermittent missing quadkey value

### ISSUE THREAD

**Issue by captaincoordinates** [sparkgeo/tile-id-api#9]
It appears that returned image tiles are occasionally missing the quadkey tile identifier. There is limited information at this time.

**Comment by matthewscottgordon** [comment]
I haven't been able to reproduce this. Do you have any more information at all? How often does it happen? Are the certain tiles or situations where it always or usually fails or does it just seem to be completely random?

**Comment by captaincoordinates** [comment]
Unfortunately no, it's been on my to-do list to investigate for a while. I have seen it happen once or twice, but never a clear indication why it would fail in such a way. My only theory was that it's somehow related to concurrency and that requesting lots of tiles concurrently might trigger it. Perhaps additional logging, or a review of any existing logs, would help direct the investigation.
